from AutoJornal import AutoJornal


# 1. CREAR BASE DE DATOS CON INFO BÁSICA Y NECESARIA
# 2. LEER INFORME VIEJO DE HORAS EN BASE DE DATOS Y CREAR INFORME NUEVO (AMBOS COMO PDF Y COMO FILA EN LA BASE DE DATOS)
# 3. ENVIAR INFORME DE HORAS ACTUALIZADO A CORRADA PARA QUE LA FIRME
# 4. TODO: VERIFICAR SI CORRADA CONTESTÓ CON LA FIRMA SUYA
# 5. TODO: ENVIAR DOCUMENTO FIRMADO A ROSITA


def main():
	aj = AutoJornal()
	aj.AddReport()
	# aj.ListenForSignedResponse()
	# aj.ForwardSignedResponse()


if __name__ == '__main__':
	main()
